export const articles = [
  {
    id: 'h-001',
    slug: 'washington-pivots-india-watches',
    headline: "Washington Pivots, and India Watches the Door",
    dek: "The latest White House signal on tariffs is less about China than it is about how middle powers price risk.",
    desk: 'united-states',
    region: 'Americas',
    subRegion: 'North America',
    country: 'United States',
    topic: 'politics',
    writer: { name: 'Aarav Mehta', role: 'Senior Correspondent, US Desk' },
    filed: { city: 'New Delhi', date: '2026-05-09' },
    lastUpdated: '2026-05-09T08:42:00+05:30',
    readTimeMin: 6,
    isHero: true,
    isEditorPick: false,
    pulseRank: null,
    image: "/src/assets/images/regenerated_image_1778333424993.png",
    body: "When the announcement came out of Washington on Wednesday morning, the response in South Block was studied silence — the kind that does not mean indifference.\n\nFor New Delhi, the question is not whether the tariff regime will hold; it is whether the United States now reads middle-power hedging as defection or as strategy. The shift indicates a broader recalibration of how economic statecraft is employed in the Pacific theater, often leaving regional partners to decipher intent from footnotes rather than direct dialogue."
  },
  {
    id: 'p-001',
    slug: 'pulse-stock-rally',
    headline: "Sensex reaches historic high as manufacturing data beats estimates",
    dek: "Indian indices surged as factory output recorded its strongest growth in three quarters.",
    desk: 'india',
    region: 'India',
    country: 'India',
    topic: 'politics',
    writer: { name: 'Bharat Lens Staff', role: 'Update' },
    filed: { city: 'Mumbai', date: '2026-05-09' },
    lastUpdated: '2026-05-09T10:15:00+05:30',
    readTimeMin: 1,
    isHero: false,
    isEditorPick: false,
    pulseRank: 1,
    image: "/src/assets/images/regenerated_image_1778330265102.png",
    body: ""
  },
  {
    id: 'p-002',
    slug: 'pulse-dhaka-transition',
    headline: "Dhaka transition council meets to discuss interim cabinet expansion",
    dek: "Regional stability remains the focus as Bangladesh navigates its governance transition.",
    desk: 'bangladesh',
    region: 'Asia',
    subRegion: 'South Asia',
    country: 'Bangladesh',
    topic: 'politics',
    writer: { name: 'Bharat Lens Staff', role: 'Update' },
    filed: { city: 'Dhaka', date: '2026-05-09' },
    lastUpdated: '2026-05-09T09:55:00+05:30',
    readTimeMin: 1,
    isHero: false,
    isEditorPick: false,
    pulseRank: 2,
    body: ""
  },
  {
    id: 'p-003',
    slug: 'pulse-chip-fab',
    headline: "Major semiconductor firm finalizes land deal for Gujarat facility",
    dek: "The multi-billion dollar investment marks a significant step for India's silicon ambitions.",
    desk: 'india',
    region: 'India',
    country: 'India',
    topic: 'technology',
    writer: { name: 'Bharat Lens Staff', role: 'Update' },
    filed: { city: 'Gandhinagar', date: '2026-05-09' },
    lastUpdated: '2026-05-09T09:30:00+05:30',
    readTimeMin: 1,
    isHero: false,
    isEditorPick: false,
    pulseRank: 3,
    image: "/src/assets/images/regenerated_image_1778330281401.png",
    body: ""
  },
  {
    id: 'p-004',
    slug: 'pulse-himalayan-border',
    headline: "Local trade resumes at key Himalayan border post after brief closure",
    dek: "The reopening of the trade route is seen as a de-escalation signal in the high-altitude region.",
    desk: 'india',
    region: 'India',
    country: 'India',
    topic: 'politics',
    writer: { name: 'Bharat Lens Staff', role: 'Update' },
    filed: { city: 'Leh', date: '2026-05-09' },
    lastUpdated: '2026-05-09T08:50:00+05:30',
    readTimeMin: 1,
    isHero: false,
    isEditorPick: false,
    pulseRank: 4,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800",
    body: ""
  },
  {
    id: 'p-005',
    slug: 'pulse-lithium-reserve',
    headline: "Geological survey identifies new lithium clusters in Rajasthan",
    dek: "The discovery could significantly boost India's transition to electric mobility.",
    desk: 'india',
    region: 'India',
    country: 'India',
    topic: 'environment',
    writer: { name: 'Bharat Lens Staff', role: 'Update' },
    filed: { city: 'Jaipur', date: '2026-05-09' },
    lastUpdated: '2026-05-09T08:15:00+05:30',
    readTimeMin: 1,
    isHero: false,
    isEditorPick: false,
    pulseRank: 5,
    image: "https://images.unsplash.com/photo-1578319400155-ac9018597375?auto=format&fit=crop&q=80&w=800",
    body: ""
  },
  {
    id: 'asia-001',
    slug: 'tokyo-hydrogen-grid',
    headline: "Tokyo Unveils World's Largest Urban Hydrogen Power Grid",
    dek: "Japan's capital is betting on a decentralized hydrogen network to power its futuristic skyline.",
    desk: 'japan',
    region: 'Asia',
    subRegion: 'East Asia',
    country: 'Japan',
    topic: 'technology',
    writer: { name: 'Bharat Lens', role: 'East Asia Tech Correspondent' },
    filed: { city: 'Tokyo', date: '2026-05-09' },
    lastUpdated: '2026-05-09T11:20:00+09:00',
    readTimeMin: 7,
    isHero: false,
    isEditorPick: false,
    pulseRank: null,
    image: "https://images.unsplash.com/photo-1519389950473-acc7b968b601?auto=format&fit=crop&q=80&w=800",
    body: "The green hydrogen initiative marks a radical departure from traditional centralized power plants, aiming for a zero-emission urban model by 2040."
  },
  {
    id: 'africa-001',
    slug: 'nairobi-fintech-hub',
    headline: "Silicon Savannah: Nairobi’s Fintech Expansion Across East Africa",
    dek: "Kenyan startups are now exporting mobile payment solutions to traditional markets in Europe.",
    desk: 'kenya',
    region: 'Africa',
    country: 'Kenya',
    topic: 'culture',
    writer: { name: 'Aditi Rao', role: 'Africa Bureau' },
    filed: { city: 'Nairobi', date: '2026-05-08' },
    lastUpdated: '2026-05-09T09:00:00+03:00',
    readTimeMin: 6,
    isHero: false,
    isEditorPick: true,
    pulseRank: null,
    image: "/src/assets/images/regenerated_image_1778336887857.png",
    body: "What started as a mobile-money revolution is now a sophisticated banking layer that is reshaping how the continent interacts with global capital flows."
  },
  {
    id: 'europe-001',
    slug: 'brussels-ai-regulation',
    headline: "Brussels Sets New Global Standard for Algorithmic Sovereignty",
    dek: "The EU's latest AI legislation is forcing silicon giants to rethink data residency.",
    desk: 'europe',
    region: 'Europe',
    topic: 'politics',
    writer: { name: 'Bharat Lens', role: 'Brussels Correspondent' },
    filed: { city: 'Brussels', date: '2026-05-09' },
    lastUpdated: '2026-05-09T10:45:00+01:00',
    readTimeMin: 8,
    isHero: false,
    isEditorPick: false,
    pulseRank: null,
    image: "https://images.unsplash.com/photo-1549110667-31320473a21e?auto=format&fit=crop&q=80&w=800",
    body: "The AI Act 2.0 introduces strict 'digital border' requirements that could fragment the global internet as we know it."
  },
  {
    id: 'sa-001',
    slug: 'amazon-conservation-tech',
    headline: "Satellite Diplomacy: Brazil Uses Real-Time AI to Guard the Amazon",
    dek: "A new joint initiative between Brazil and India brings low-cost satellite monitoring to the rainforest.",
    desk: 'brazil',
    region: 'Americas',
    subRegion: 'South America',
    country: 'Brazil',
    topic: 'environment',
    writer: { name: 'Sanjay Gupta', role: 'South America Editor' },
    filed: { city: 'Brasília', date: '2026-05-08' },
    lastUpdated: '2026-05-09T08:15:00-03:00',
    readTimeMin: 9,
    isHero: false,
    isEditorPick: true,
    pulseRank: null,
    image: "/src/assets/images/regenerated_image_1778336891759.png",
    body: "The collaboration highlights a growing trend of Global South nations sharing high-tech solutions for local problems without Western intermediation."
  },
  {
    id: 'e-001',
    slug: 'silicone-valley-bengaluru',
    headline: "The Glass Floor of the Silicon Plateau",
    dek: "Bengaluru's tech boom is hitting a physical limit that software cannot solve.",
    desk: 'india',
    region: 'India',
    country: 'India',
    topic: 'technology',
    writer: { name: 'Isha Prasad', role: 'Technology Editor' },
    filed: { city: 'Bengaluru', date: '2026-05-08' },
    lastUpdated: '2026-05-09T07:30:00+05:30',
    readTimeMin: 8,
    isHero: false,
    isEditorPick: true,
    pulseRank: null,
    image: "/src/assets/images/regenerated_image_1778336895138.png",
    body: "The traffic on Outer Ring Road has become more than a meme; it is a structural inhibitor to the very productivity the city promises. As the Silicon Plateau expands, the infrastructure beneath it remains fixed in an era that did not anticipate this density.\n\nFrom a Global South perspective, the Bengaluru experience is a cautionary tale of rapid urbanization disconnected from civic planning. While the software exports reach record highs, the daily commute for those building it becomes an exercise in endurance. It remains to be seen if the new metro corridors can alleviate a congestion that is now deeply baked into the city's geography."
  },
  {
    id: 'wa-001',
    slug: 'saudi-giga-infrastructure',
    headline: "NEOM’s Vertical Reality: A Report from the Line",
    dek: "The structural skeleton of the Line begins to pierce the Tabuk horizon.",
    desk: 'saudi-arabia',
    region: 'Asia',
    subRegion: 'West Asia',
    country: 'Saudi Arabia',
    topic: 'technology',
    writer: { name: 'Bharat Lens', role: 'West Asia Bureau' },
    filed: { city: 'Tabuk', date: '2026-05-09' },
    lastUpdated: '2026-05-09T14:20:00+03:00',
    readTimeMin: 10,
    isHero: false,
    isEditorPick: false,
    pulseRank: null,
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&q=80&w=800",
    body: "Standing at the edge of the excavation, the scale of Saudi Arabia's vision is both terrifying and awesome. It is a physical manifestation of a nation's desire to rewrite its economic destiny in stone and steel."
  },
  {
    id: 'us-002',
    slug: 'midterm-realignment-strategies',
    headline: "The Silent Realignment: Why Local Primaries Are Testing National Unity",
    dek: "Across key swing states, the divide between base expectations and general election viability is widening.",
    desk: 'united-states',
    region: 'Americas',
    subRegion: 'North America',
    country: 'United States',
    topic: 'politics',
    writer: { name: 'Ananya Sharma', role: 'Chief Political Correspondent' },
    filed: { city: 'Washington, D.C.', date: '2026-05-09' },
    lastUpdated: '2026-05-09T16:45:00-04:00',
    readTimeMin: 7,
    isHero: false,
    isEditorPick: false,
    pulseRank: null,
    image: "/src/assets/images/regenerated_image_1778330536230.png",
    body: "The landscape of American politics is shifting under the weight of localized grievances that used to stay at the municipal level but are now being nationalized through digital networks. What we are seeing in Pennsylvania and Ohio is a preview of a possible 2028 reality."
  },
  {
    id: 'us-003',
    slug: 'california-energy-grid-shift',
    headline: "California’s Grid Resilience: A New Blueprint for the West",
    dek: "New storage solutions are finally catching up with the state's aggressive solar output.",
    desk: 'united-states',
    region: 'Americas',
    subRegion: 'North America',
    country: 'United States',
    topic: 'environment',
    writer: { name: 'Bharat Lens', role: 'Environment Editor' },
    filed: { city: 'Sacramento', date: '2026-05-09' },
    lastUpdated: '2026-05-09T14:15:00-07:00',
    readTimeMin: 6,
    isHero: false,
    isEditorPick: true,
    pulseRank: null,
    image: "/src/assets/images/regenerated_image_1778330538230.png",
    body: "The challenge of the 'duck curve'—the massive overproduction of solar in the midday followed by a sharp drop at sunset—is being solved by a decentralized battery initiative that has turned the tide for California's energy independence."
  },
  {
    id: 'us-004',
    slug: 'quantum-valley-mid-atlantic',
    headline: "Forget Palo Alto: The Quantum Valley is Rising in D.C.",
    dek: "Federal funding and academic clusters are creating a new hardware-focused tech hub.",
    desk: 'united-states',
    region: 'Americas',
    subRegion: 'North America',
    country: 'United States',
    topic: 'technology',
    writer: { name: 'Rohan Kapoor', role: 'Innovation Reporter' },
    filed: { city: 'Arlington', date: '2026-05-09' },
    lastUpdated: '2026-05-09T12:30:00-04:00',
    readTimeMin: 8,
    isHero: false,
    isEditorPick: false,
    pulseRank: null,
    image: "/src/assets/images/regenerated_image_1778337189334.png",
    body: "Quantum computing requires a level of physical shielding and laboratory infrastructure that standard co-working spaces cannot provide. As result, the industry is gravitating towards the East Coast's established scientific corridors."
  },
  {
    id: 'us-005',
    slug: 'wall-street-algorithm-shift',
    headline: "The New Alchemists: How AI Is Redefining Risk on Wall Street",
    dek: "Proprietary models are moving beyond pattern matching to predictive causality.",
    desk: 'united-states',
    region: 'Americas',
    subRegion: 'North America',
    country: 'United States',
    topic: 'business',
    writer: { name: 'Bharat Lens', role: 'Financial Correspondent' },
    filed: { city: 'New York', date: '2026-05-09' },
    lastUpdated: '2026-05-09T11:00:00-04:00',
    readTimeMin: 7,
    isHero: false,
    isEditorPick: true,
    pulseRank: null,
    image: "/src/assets/images/regenerated_image_1778333580622.png",
    body: "High-frequency trading was the first wave. The second wave is causal AI, which can explain why a market shift is happening, allowing firms to react before the trend fully manifests."
  },
  {
    id: 'us-006',
    slug: 'broadway-digital-revival',
    headline: "Broadway’s Digital Stage: The Hybrid Future of Theater",
    dek: "Immersive tech is bringing live performances to global audiences in real-time.",
    desk: 'united-states',
    region: 'Americas',
    subRegion: 'North America',
    country: 'United States',
    topic: 'culture',
    writer: { name: 'Priya Das', role: 'Arts Critic' },
    filed: { city: 'New York', date: '2026-05-08' },
    lastUpdated: '2026-05-09T09:30:00-04:00',
    readTimeMin: 5,
    isHero: false,
    isEditorPick: false,
    pulseRank: null,
    image: "/src/assets/images/regenerated_image_1778333583200.png",
    body: "The empty seats of the pandemic era forced a radical rethink. Today, Broadway is not just a street in Manhattan; it is a globally accessible digital platform."
  },
  {
    id: 'us-007',
    slug: 'mls-global-talent-surge',
    headline: "MLS at the Crossroads: Chasing the World’s Elite",
    dek: "American soccer is leveraging its infrastructure to become a primary destination for South American talent.",
    desk: 'united-states',
    region: 'Americas',
    subRegion: 'North America',
    country: 'United States',
    topic: 'sports',
    writer: { name: 'Arjun Singh', role: 'Bharat Lens Staff' },
    filed: { city: 'Miami', date: '2026-05-09' },
    lastUpdated: '2026-05-09T10:20:00-04:00',
    readTimeMin: 6,
    isHero: false,
    isEditorPick: false,
    pulseRank: null,
    image: "/src/assets/images/regenerated_image_1778337186686.png",
    body: "The transition of MLS from a 'retirement league' to a 'development and export league' is complete. The influx of young stars from Brazil and Argentina has raised the technical floor of American soccer."
  }
];

